name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7
          
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib list
          
      - name: Clean previous build
        run: |
          rm -rf ./bin
          mkdir ./bin

      
          
      - name: Compile
        run: haxe build.hxml
        
      - name: Generate version file
        run: |
          echo "Last updated: $(date -u)" > ./bin/version.txt
          echo "Commit: $GITHUB_SHA" >> ./bin/version.txt
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './bin'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
